version: '3.8'
services:
  jenkins:
    build: .
    container_name: jenkins
    environment:
      - JENKINS_ADMIN_USER=${JENKINS_ADMIN_USER}
      - JENKINS_ADMIN_PASS=${JENKINS_ADMIN_PASS}
      - SLACK_TOKEN=${SLACK_TOKEN}
    ports:
      - 8080:8080
      - 50000:50000
    restart: on-failure
    volumes:
      - /${PWD}/jenkins_config:/var/jenkins_home
      - ./casc_configs:/var/jenkins_home/casc_configs
      - /var/run/docker.sock:/var/run/docker.sock
